version: "3"

services:
  db:
    # 사용 이미지
    image: mysql:5.7
    # 컨테이너 실행 시 재시작
    restart: always
    # 컨테이너 이름
    container_name: mysql
    # 볼륨 설정
    volumes:
      - ./mysqldata:/var/lib/mysql
    # 환경 변수 설정
    environment:
      - MYSQL_ROOT_PASSWORD=root
    # 커맨드 설정
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    # 컨테이너 내부:외부 포트 설정
    ports:
      - "3307:3306"